var age = 25;
age = true;
console.log(age);
age = "hello";
console.log(age);
age = { name: "Donia" };
console.log(age);
var mixed = [];
mixed.push('jiji');
mixed.push(false);
mixed.push(5);
console.log(mixed);
var person;
person = { name: 'Donia', age: 20 };
console.log(person);
